### ISSUE TITLE
ImportError & ModuleNotFoundError

### ISSUE THREAD

**Issue by lynnjeoun** [WeixiongLin/PMC-CLIP#1]
Hi, authors
Thank you for sharing your work.
While I was reproducing your code for testing, I found out there are several codes missing.

Representatively, I get these two errors below :
1. ImportError: cannot import name 'VisualTransformer' from 'pmc_clip.model.blocks'
2. ModuleNotFoundError: No module named 'pmc_clip.model.mlm'

I have looked up the whole code but 'VisualTranformer' cannot be found in blocks.py, and there is no such 'mlm.py' in pmc_clip.model.

Do you have any plans to release those two parts too?

Thank you

**Comment by WeixiongLin** [comment]
Thanks for raising this issue, would you give me more details so that I can identify the specific source of the bug.
Information such as the location of ImportError would help a lot.

p.s. I promise to release all the code to community, so feel free to raise issues (*^_^*).

**Comment by pengyu965** [comment]
File "./PMC-CLIP/src/pmc_clip/model/base_model.py", line 17, in <module>
    from .blocks import ModifiedResNet, LayerNorm, QuickGELU, VisualTransformer, Transformer
ImportError: cannot import name 'VisualTransformer' from 'pmc_clip.model.blocks' (./PMC-CLIP/src/pmc_clip/model/blocks.py)

Hi, seems like you don't have 'VisualTransformer' class in your 'block.py' code which is under 'src/pmc_clip/model/' folder. Could you please have a look into this?

**Comment by WeixiongLin** [comment]
Thank you @pengyu965 for the info, it seems that I remove `VisualTransformer` block when releasing the code. I will release the VisualTransformer in the next few days.

**Comment by WeixiongLin** [comment]
Also, as referred in our paper, we only use ResNet for model's visual encoder. The `VisualTransformer` might be less effective than ResNet according to our empirical study. Also we ourself have no pretrained weights for the `VisualTransformer` due to tight computing budget.

**Comment by SZUHvern** [comment]
| ERROR | Model config for RN50 not found; available models ['RN50_fusion1', 'RN50_fusion2', 'RN50_fusion4', 'RN50_fusion8', 'RN50x4_fusion4', 'RN50x16_fusion4', 'RN101_fusion4'].

After I delete some 'import unavaluable pakage' code
It seems that even RN50 cannot be found -_-
Thank you very much for your contribution to the community again. Please modify the code for ease of use.

**Comment by pengyu965** [comment]
For everyone who would like to solve the visual_transformer not found error. I found the vision_transformer from the hugging face: https://github.com/dandelin/ViLT/blob/762fd3975c180db6fc88f577cf39549983fa373a/vilt/modules/vision_transformer.py (which is the same link mentioned in the comments in pmc_clip.py).
Simply copy paste the code and rename the vision_transformer class accordingly would make the modeling part work.

@WeixiongLin Thanks for the information, I would try the resnet50.

**Comment by WeixiongLin** [comment]
> | ERROR | Model config for RN50 not found; available models ['RN50_fusion1', 'RN50_fusion2', 'RN50_fusion4', 'RN50_fusion8', 'RN50x4_fusion4', 'RN50x16_fusion4', 'RN101_fusion4'].
> 
> After I delete some 'import unavaluable pakage' code It seems that even RN50 cannot be found -_- Thank you very much for your contribution to the community again. Please modify the code for ease of use.

I believe that this error comes from the unfound model config file. So I open another issue for it. You can get my help in [Model Config Not Found](https://github.com/WeixiongLin/PMC-CLIP/issues/2)

**Comment by WeixiongLin** [comment]
> For everyone who would like to solve the visual_transformer not found error. I found the vision_transformer from the hugging face: https://github.com/dandelin/ViLT/blob/762fd3975c180db6fc88f577cf39549983fa373a/vilt/modules/vision_transformer.py (which is the same link mentioned in the comments in pmc_clip.py). Simply copy paste the code and rename the vision_transformer class accordingly would make the modeling part work.
> 
> @WeixiongLin Thanks for the information, I would try the resnet50.

Thanks, I think you are right. The ViT is compatible with our model. You can switch from RN50 to ViT if you like. Feel free to raise a PR if you want to merge ViT backbone into our codebase.

**Comment by WeixiongLin** [comment]
I would close this issue since the import error seems to be fixed. Feel free to reopen it if it's actually not solved.
