### ISSUE TITLE
How to establish the text-to-image retrival task?

### ISSUE THREAD

**Issue by pqpq17** [WeixiongLin/PMC-CLIP#13]
Hi Weixiong, so admired of your job!
I'm a beginner of medical retrival.
If I want to establish the text-to-image retrival task baesd on your pretrained model, how shouid I do?

**Comment by WeixiongLin** [comment]
Hi @pqpq17 , I appreciate your interest in our work. To use our pretrained model for downstream tasks, I recommand you to load the pretrained weights into your own model and train the prediction head only.

**Comment by WeixiongLin** [comment]
Those classic works in pretraining would provide more detailed finetuning code. I would refer you to [open-clip project](https://github.com/mlfoundations/open_clip), which is the open-source implementation of OpenAI's CLIP.

**Comment by WeixiongLin** [comment]
Feel free to reopen this issue and contact me if you need further help.
