### ISSUE TITLE
csv文件获取

### ISSUE THREAD

**Issue by wuyanlin-wyl** [WeixiongLin/PMC-CLIP#14]
感谢您的开源，请问Training训练命令中“--train-data="path/to/train.csv" --val-data="path/to/valid.csv" \”的这两个csv文件应该如何获取或构建呢

**Comment by WeixiongLin** [comment]
您好，你可以使用 [ROCO](https://github.com/razorx89/roco-dataset) 的数据集进行小规模的训练。此外我们开源了一个更大的数据集，可以用 [Build PMC-OA](https://github.com/WeixiongLin/Build-PMC-OA) 进行构建。

**Comment by WeixiongLin** [comment]
如果您有进一步的问题，欢迎重新打开这个 Issue
