### ISSUE TITLE
Training from the scratch

### ISSUE THREAD

**Issue by Kiritokingklcl** [WeixiongLin/PMC-CLIP#15]
Hi, thanks for your contribution. I have some questions about the code.
To be honest I'm learning about CLIP using medical images. So, I want to Training this model from the scratch.
Could you give me some prompt for your code?

**Comment by WeixiongLin** [comment]
Sure! Only the text encoder is inintialized from PubmedBERT in PMC-CLIP. So you can simply change the model config of text encoder.

Take `src/pmc_clip/model_configs/Fusion/RN50_fusion8.json` for an example.

```json
{
    "embed_dim": 768,
    "clip_model": "PMC_CLIP",
    "vision_cfg": {
        "image_size": 224,
        "layers": [
            3,
            4,
            6,
            3
        ],
        "width": 64,
        "patch_size": null
    },
    "text_cfg": {
        "context_length": 77,
        "vocab_size": 30522,
        "width": 768,
        "heads": 8,
        "layers": 12,
        "fusion_layers": 8,
        "bert_model_name": "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
    }
}
```
Remove the `"bert_model_name": "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"`, and it should work.

**Comment by WeixiongLin** [comment]
Feel free to reopen the issue if you need further help.
