### ISSUE TITLE
how to decode the prediction

### ISSUE THREAD

**Issue by xw2018** [WeixiongLin/PMC-CLIP#18]
Thanks for your excellent work!I wonder how to decode the prediction into natural language,can not find some decode code in this project but loss calculate

**Comment by xw2018** [comment]
感谢大佬的工作！没找到把输出numpy数组转回text的decode代码，求助

**Comment by coder1165** [comment]
Did you solve it?I also have the same problem.

**Comment by WeixiongLin** [comment]
I may need further information to help you with the issue. PMC-CLIP is designed to provide well learned visual / textual embedding. There's no decoder in PMC-CLIP actually.

**Comment by WeixiongLin** [comment]
Since there's no further question raised, I am going to close the issue for now, feel free to reopen it.
