### ISSUE TITLE
The provided weights do not match the model.

### ISSUE THREAD

**Issue by 1islist** [WeixiongLin/PMC-CLIP#19]
Hello author, when I wanted to directly use your weight file for inference verification, I found that the weight file you provided and the model were inconsistent, why is this?An error is as follows: 
the File "/ data/PMC - CLIP - the main/SRC/training/main py", line 213, in the main
model.load_state_dict(sd)
File "/ data/anaconda3 envs pmc_clip/lib/python3.8 / site - packages/torch/nn/modules/module. Py", line 2152, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PMC_CLIP:
Unexpected key(s) in state_dict: "text_encoder.embeddings.position_ids".
Did I just change it to model.load_state_dict(checkpoint, strict=false)?

**Comment by coder1165** [comment]
> Hello author, when I wanted to directly use your weight file for inference verification, I found that the weight file you provided and the model were inconsistent, why is this?An error is as follows: the File "/ data/PMC - CLIP - the main/SRC/training/main py", line 213, in the main model.load_state_dict(sd) File "/ data/anaconda3 envs pmc_clip/lib/python3.8 / site - packages/torch/nn/modules/module. Py", line 2152, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for PMC_CLIP: Unexpected key(s) in state_dict: "text_encoder.embeddings.position_ids". Did I just change it to model.load_state_dict(checkpoint, strict=false)?

Did you fixed the problem? I met this issue too.

**Comment by WeixiongLin** [comment]
My bad, I modified the model structure after the training progress finished. I might need a couple of days to fix this.

**Comment by 1islist** [comment]
> 我的错，我在训练过程结束后修改了模型结构。我可能需要几天时间才能解决这个问题。

Thank you for your reply and look forward to your solution. Thank you.

**Comment by 1islist** [comment]
> My bad, I modified the model structure after the training progress finished. I might need a couple of days to fix this.

Author Hello, are you done with the code changes?

**Comment by WeixiongLin** [comment]
Hi there! We finally fix the bug with the help of @zhaoziheng . He write a colab notebook to demonstrate how to load the chekcpoint weights. I have run the test and it should work well.

**Comment by WeixiongLin** [comment]
It seems that the new weight file provided has solved the problem. I am going to close this issue, feel free to reopen it if you need further help.

**Comment by Mike-ihr** [comment]
> It seems that the new weight file provided has solved the problem. I am going to close this issue, feel free to reopen it if you need further help.

I wanna know where is the new weight file. the checkpoint in huggingface is wrong.
