### ISSUE TITLE
Model config not found

### ISSUE THREAD

**Issue by WeixiongLin** [WeixiongLin/PMC-CLIP#2]
| ERROR | Model config for RN50 not found; available models ['RN50_fusion1', 'RN50_fusion2', 'RN50_fusion4', 'RN50_fusion8', 'RN50x4_fusion4', 'RN50x16_fusion4', 'RN101_fusion4'].

After I delete some 'import unavaluable pakage' code
It seems that even RN50 cannot be found -_-
Thank you very much for your contribution to the community again. Please modify the code for ease of use.

_Originally posted by @SZUHvern in https://github.com/WeixiongLin/PMC-CLIP/issues/1#issuecomment-1552360227_

**Comment by WeixiongLin** [comment]
Would you provide your full command here so that I can identify the exact error.
I think the error could comes from the mismatch between `model config command` and `model config file`.
Which means you should appoint the model config file with `--model` in the command, for example:
> python -m training.main \
> --dataset-type "csv" --csv-separator "," --save-frequency 5 \
> --report-to tensorboard \
> --train-data="path/to/train.csv" --val-data="path/to/valid.csv" \
> --csv-img-key image --csv-caption-key caption \
> --warmup 500 --batch-size=8 --lr=1e-4 --wd=0.1 --epochs=100 --workers=8 \
> **--model RN50_fusion4** --hugging-face --mlm --crop-scale 0.5

And that model config file `RN50_fusion4` should exist in folder `src/pmc_clip/model_configs`.

**Comment by WeixiongLin** [comment]
Feel free to @me if the problem is not solved.

**Comment by SZUHvern** [comment]
yes, I just run the training.main.py by default setting, 
where the problem is in params.py setting:
    parser.add_argument(
        "--model",
        type=str,
        default="RN50",
        help="Name of the vision backbone to use.",
    )

it's work when I modify the default name

**Comment by WeixiongLin** [comment]
Glad to help, and I will close this issue for now. Feel free to reopen it if this issue is not solved completely.
