### ISSUE TITLE
Weights checkpoint for the main paper experimental results

### ISSUE THREAD

**Issue by muzairkhattak** [WeixiongLin/PMC-CLIP#21]
Hi @WeixiongLin,

Thank you for open-sourcing this amazing work!

Could you kindly confirm if the model weights provided in this repository were used to produce the experimental results reported in your main paper? If not, could you please provide the model checkpoint used for the experiments?

Kind regards,
Muhammad Uzai

**Comment by WeixiongLin** [comment]
Thanks for your attention. The model weights is host on huggingface. I refer you to the colab provided in readme, where we demonstrate the preparation and the use of pmc-clip.

Feel free to reopen the issue if it's not solved.
