### ISSUE TITLE
Missing Function of 'train_one_epoch'

### ISSUE THREAD

**Issue by SZUHvern** [WeixiongLin/PMC-CLIP#3]
There is no 'train_one_epoch' function in 'training.train/'
where leading the error in main.py at:
1. 'from training.train import train_one_epoch' ;
2. trainer, evaluator = {'PMC_CLIP': (train_one_epoch_mlm, evaluate),}.get(args.clip_model, (train_one_epoch, evaluate));

**Comment by WeixiongLin** [comment]
Thanks for your issue. This missing function is actually not required for training, so I recommend not to import `train_one_epoch`. That's to say, you can remove `import train_one_epoch` and keep `import train_one_epoch_mlm` only.

**Comment by SZUHvern** [comment]
So adjust 
'trainer, evaluator = {'PMC_CLIP': (train_one_epoch_mlm, evaluate),}.get(args.clip_model, (train_one_epoch, evaluate))'
to
'trainer, evaluator = {'PMC_CLIP': (train_one_epoch_mlm, evaluate),}.get(args.clip_model, (train_one_epoch_mlm, evaluate))'?
Is that right?

**Comment by WeixiongLin** [comment]
Yes, that will do.

**Comment by SZUHvern** [comment]
OK, Thanks!
