### ISSUE TITLE
.json metafiles of PMC-OA

### ISSUE THREAD

**Issue by paradisetww** [WeixiongLin/PMC-CLIP#4]
I find the .jsonl metafiles you provided are the whole captions, that is, PMC-OA Beta Version. Can you provide the .jsonl metafiles of separated captions, that is, PMC-OA Version? Thanks!

**Comment by WeixiongLin** [comment]
Yes, and we have augmented PMC-OA captions with the help of GPT, we would release the new dataset by 7, July.

**Comment by WeixiongLin** [comment]
Hi @paradisetww ,we have released both PMC-OA and beta version on Huggingface-Dataset.
Checkout https://huggingface.co/datasets/axiong/pmc_oa
