### ISSUE TITLE
fine-tuning on my own dataset

### ISSUE THREAD

**Issue by Betty-J** [WeixiongLin/PMC-CLIP#5]
Hi, thanks for your work. I want try to fine-tuning on my own dataset, applied to a medical image classification task, could I directly load the checkpoints you provided? my dataset is small, around 2000 images, looking forward to your suggestions, thank you!

**Comment by WeixiongLin** [comment]
Yes of course, our checkpoint provides both image and text encoders to facilitate downstream tasks.
You would only need to load the visual encoder provided in our checkpoint for image classification task
