### ISSUE TITLE
How are demographic attributes obtained?

### ISSUE THREAD

**Issue by ys-zong** [WeixiongLin/PMC-CLIP#7]
Hi, thanks for the nice work! 

As mentioned in the paper: "We provide the sex-ratio across ages in Fig. 3(d), as we can see PMC- OAis approximately gender-balanced, with 54% males". I wonder how are the age and sex attributes obtained, and how can I get access to them? The current open-sourced dataset doesn't seem to have these information. Many thanks!

**Comment by WeixiongLin** [comment]
Hello, thanks for your interest in our work.

We actually use [regrex expressions](https://en.wikiversity.org/wiki/Regular_expressions) to match those patients' age and gender mentioned in corpus. We didn't release that since it's just a statistic analysis of our dataset.

**Comment by ys-zong** [comment]
Got it. Is possible to release the code for the regex matches? Thanks!

**Comment by WeixiongLin** [comment]
It's temporary code for analysis, so I didn't keep that in the repo.
But the gist is to match strs like `a 33 year old man ...`, in such case, the regrex is `a ^[0-9]* year old man`.

Hope this message helpful to you.
