### ISSUE TITLE
How to finetune on RadVQA and Slake?

### ISSUE THREAD

**Issue by ecoxial2007** [WeixiongLin/PMC-CLIP#8]
Hello,

I am interested in using your PMC-CLIP model for a project involving the RadVQA and SLAKE datasets. I was wondering if you could provide some guidance on how to finetune your model on these datasets.

Specifically, I am interested in understanding how to fuse the question and image embeddings for these tasks. Are there any specific techniques or methods that you would recommend for this?

Additionally, I noticed in your paper that you added 10 learnable prompt vectors for the questions and answers. Could you provide some more details on how this was implemented? 

If there are any relevant papers or projects that you could point me to for reference, that would be greatly appreciated.

Thank you for your time and assistance.

**Comment by WeixiongLin** [comment]
Thanks for your interest, we have to be brief about the finetuning procedure due to the limited size of MICCAI.
For finetuning, the learnable vectors are used for downstream task adaptation. And it's implemented with `[pytorch.Embedding`.

Hope this messsage helpful to you.
