### ISSUE TITLE
zero-shot prediction with other datasets

### ISSUE THREAD

**Issue by YinqiCai** [WeixiongLin/PMC-CLIP#9]
Hi, thanks for your good work!

I want to try zero-shot classification with other datasets, but I don't know how to load and use your model easily, it seems that I have to change some of your code. I wonder know is there an easy way to load and use the visual encoder and text encoder just like CLIP/open_clip? Or how can I write some code to try classification? 

Thanks for your code , looking forward to your reply!

**Comment by YinqiCai** [comment]
I load resnet50 and PubMedBERT respectively, and I solve my problem. Thanks for your code again!

**Comment by YinqiCai** [comment]
I load resnet50 and PubMedBERT respectively, and I solve my problem. Thanks for your code again!

**Comment by coder1165** [comment]
> 我分别加载了 resnet50 和 PubMedBERT，解决了我的问题。再次感谢您的代码！

Hi I also have same purpose,Could you please share your code
